name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  ci-pipeline:
    uses: optisense/devops-workflows/.github/workflows/REUSABLE_ci_backend.yaml@main
    with:
      package_manager: poetry
      python_version: "3.11"
      runner: ubuntu-latest
      skip_sonarqube: true
    secrets: inherit
